"""add user profile field

Revision ID: 0738bb7e967d
Revises: 31ec2d04479c
Create Date: 2026-07-18 21:24:40.283008

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0738bb7e967d"
down_revision: str | Sequence[str] | None = "31ec2d04479c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("display_name", sa.String(length=100), nullable=False)
    )
    op.add_column("users", sa.Column("is_superuser", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_superuser")
    op.drop_column("users", "display_name")
    # ### end Alembic commands ###
