"""add token version to users

Revision ID: 0e36da76c55d
Revises: 1e22ae6e25af
Create Date: 2026-09-28 20:12:27.684959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e36da76c55d'
down_revision: Union[str, Sequence[str], None] = '1e22ae6e25af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token_version', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('users', 'token_version')
    # ### end Alembic commands ###
